title: Harish Sarma
author: Harish Sarma
description: Software engineer, builder, automation maker and curious explorer.
url: "https://harishsarmav.github.io"
baseurl: "/harishsarma_v"
lang: en-IN
timezone: Asia/Kolkata
future: true
permalink: /blog/:title/
date_format: "%B %-d, %Y"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

social:
  email: harishsarma.v@gmail.com
  github: https://github.com/harishsarmav
  linkedin: https://www.linkedin.com/in/harishsarmav/
  instagram: https://www.instagram.com/the.harish.way/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      social-share: false
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - node_modules
  - vendor
  - .bundle
  - tmp
  - Appraisals
  - README.md
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
